version: '3'

services:
  php:
    restart: unless-stopped
    build:
      target: prod
    expose: !reset []
    volumes: !override
      - storage:/app/storage
      - ./storage/logs:/app/storage/logs
      - caddy_data:/data
      - caddy_config:/config