version: '3'
services:
  php:
    build:
      context: .
      target: dev
    volumes:
      - .:/app
      - caddy_data:/data
      - caddy_config:/config
    expose:
      - 9000
      - 9003
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    environment:
      SERVER_NAME: ${CADDY_SERVER_NAME}
    tty: true

volumes:
  caddy_data: {}
  caddy_config: {}
  storage: {}