version: '3'
services:
  php:
    build:
      dockerfile: docker/php/Dockerfile
      context: .
    restart: "unless-stopped"
    volumes:
      - v_public:/var/www/html/public
    networks:
      - n_backend

  nginx:
    build:
      dockerfile: docker/nginx/Dockerfile
      context: .
    depends_on:
      - php
    restart: "unless-stopped"
    volumes:
      - type: volume
        source: v_public
        target: /var/www/html/public
        volume:
          nocopy: true
    ports:
      - 8000:80
    networks:
      - n_backend


volumes:
  v_public: {}

networks:
  n_backend: